export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";
export const GET_POSTS_BULK_SUCCESS = "GET_POSTS_BULK_SUCCESS";
export const GET_POSTS_BULK_FAIL = "GET_POSTS_BULK_FAIL";

